// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CovidStats
{
    using System.Linq;
    using System.Collections.Generic;
    using CovidStats.DailyEpidemiology;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DailyEpidemiologyXml : DailyEpidemiologyXmlBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<Days>\r\n");
            
            #line 8 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
  
    var allChoNames= Days.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.CHORates!=null)
                        pList.AddRange(pItem.CHORates.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allChoNames.Sort();

    var allCcaNames= Days.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.CCARates!=null)
                        pList.AddRange(pItem.CCARates.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allCcaNames.Sort();

    var allHospitalisedNames= Days.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.Hospitalised!=null)
                        pList.AddRange(pItem.Hospitalised.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allHospitalisedNames.Sort();

    var allCountyNames= Days.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.CountyRates!=null)
                        pList.AddRange(pItem.CountyRates.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allCountyNames.Sort();
    for(var i = Days.Min(pX=>pX.FromDate);  i < Days.Max(pX=>pX.FromDate); i= i.AddDays(1)) { 
        var current = Days.FirstOrDefault(pX=>pX.FromDate == i);

            
            #line default
            #line hidden
            this.Write("    <Day>\r\n        <SourceFileName>");
            
            #line 48 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current?.SourceFileName ?? "MISSING")));
            
            #line default
            #line hidden
            this.Write("</SourceFileName>\r\n        <FromDate>");
            
            #line 49 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.ToShortDateString()));
            
            #line default
            #line hidden
            this.Write("</FromDate>\r\n        <ToDate>");
            
            #line 50 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.ToDate : i.AddDays(14)).ToShortDateString()));
            
            #line default
            #line hidden
            this.Write("</ToDate>\r\n        <PreparedDate>");
            
            #line 51 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.PreparedDate.ToShortDateString() : "")));
            
            #line default
            #line hidden
            this.Write("</PreparedDate>\r\n        <TotalConfirmedCasesAbs>");
            
            #line 52 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.TotalConfirmedCases.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</TotalConfirmedCasesAbs>\r\n        <TotalConfirmedCasesPcnt>");
            
            #line 53 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.TotalConfirmedCases.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</TotalConfirmedCasesPcnt>\r\n        <SexMaleFemaleRatio>");
            
            #line 54 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.SexCharacteristics.MaleFemaleRatio.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</SexMaleFemaleRatio>\r\n        <SexMaleAbs>");
            
            #line 55 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.SexCharacteristics.Male.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</SexMaleAbs>\r\n        <SexMalePcnt>");
            
            #line 56 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.SexCharacteristics.Male.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</SexMalePcnt>\r\n        <SexFemaleAbs>");
            
            #line 57 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.SexCharacteristics.Female.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</SexFemaleAbs>\r\n        <SexFemalePcnt>");
            
            #line 58 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.SexCharacteristics.Female.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</SexFemalePcnt>\r\n        <SexUnknownAbs>");
            
            #line 59 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.SexCharacteristics.Unknown.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</SexUnknownAbs>\r\n        <SexUnknownPcnt>");
            
            #line 60 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.SexCharacteristics.Unknown.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</SexUnknownPcnt>\r\n        <AgeMedian>");
            
            #line 61 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.MedianAge.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</AgeMedian>\r\n        <AgeMean>");
            
            #line 62 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.MeanAge.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</AgeMean>\r\n        <Age0To4Abs>");
            
            #line 63 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age0To4.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age0To4Abs>\r\n        <Age0To4Pcnt>");
            
            #line 64 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age0To4.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age0To4Pcnt>\r\n        <Age5To12Abs>");
            
            #line 65 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age5To12.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age5To12Abs>\r\n        <Age5To12Pcnt>");
            
            #line 66 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age5To12.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age5To12Pcnt>\r\n        <Age13To18Abs>");
            
            #line 67 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age13To18.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age13To18Abs>\r\n        <Age13To18Pcnt>");
            
            #line 68 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age13To18.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age13To18Pcnt>\r\n        <Age19To24Abs>");
            
            #line 69 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age19To24.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age19To24Abs>\r\n        <Age19To24Pcnt>");
            
            #line 70 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age19To24.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age19To24Pcnt>\r\n        <Age25To34Abs>");
            
            #line 71 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ?  current.AgeCharacteristics.Age25To34.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age25To34Abs>\r\n        <Age25To34Pcnt>");
            
            #line 72 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age25To34.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age25To34Pcnt>\r\n        <Age35To44Abs>");
            
            #line 73 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ?  current.AgeCharacteristics.Age35To44.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age35To44Abs>\r\n        <Age35To44Pcnt>");
            
            #line 74 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age35To44.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age35To44Pcnt>\r\n        <Age45To54Abs>");
            
            #line 75 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ?  current.AgeCharacteristics.Age45To54.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age45To54Abs>\r\n        <Age45To54Pcnt>");
            
            #line 76 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age45To54.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age45To54Pcnt>\r\n        <Age55To64Abs>");
            
            #line 77 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ?  current.AgeCharacteristics.Age55To64.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age55To64Abs>\r\n        <Age55To64Pcnt>");
            
            #line 78 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age55To64.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age55To64Pcnt>\r\n        <Age65To74Abs>");
            
            #line 79 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ?  current.AgeCharacteristics.Age65To74.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age65To74Abs>\r\n        <Age65To74Pcnt>");
            
            #line 80 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age65To74.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age65To74Pcnt>\r\n        <Age75To84Abs>");
            
            #line 81 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ?  current.AgeCharacteristics.Age75To84.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age75To84Abs>\r\n        <Age75To84Pcnt>");
            
            #line 82 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age75To84.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age75To84Pcnt>\r\n        <Age85PlusAbs>");
            
            #line 83 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age85Plus.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age85PlusAbs>\r\n        <Age85PlusPcnt>");
            
            #line 84 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.Age85Plus.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Age85PlusPcnt>\r\n        <AgeUnknownAbs>");
            
            #line 85 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.AgeUnknown.Absolute.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</AgeUnknownAbs>\r\n        <AgeUnknownPcnt>");
            
            #line 86 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((current!=null ? current.AgeCharacteristics.AgeUnknown.Percent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</AgeUnknownPcnt>");
            
            #line 86 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"

        foreach(var cho in allChoNames) {
            var inc = current?.CHORates?.FirstOrDefault(pX=>pX.Name==cho);

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 90 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cho));
            
            #line default
            #line hidden
            this.Write("Abs>");
            
            #line 90 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.ConfirmedCases.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 90 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cho));
            
            #line default
            #line hidden
            this.Write("Abs>\r\n        <");
            
            #line 91 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cho));
            
            #line default
            #line hidden
            this.Write("Rate>");
            
            #line 91 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.IncidencePer100k.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 91 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cho));
            
            #line default
            #line hidden
            this.Write("Rate>\r\n");
            
            #line 92 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"

        }

        foreach(var county in allCountyNames) {
            var inc = current?.CountyRates?.FirstOrDefault(pX=>pX.Name==county);

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 98 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(county));
            
            #line default
            #line hidden
            this.Write("Abs>");
            
            #line 98 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.ConfirmedCases.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 98 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(county));
            
            #line default
            #line hidden
            this.Write("Abs>\r\n        <");
            
            #line 99 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(county));
            
            #line default
            #line hidden
            this.Write("Rate>");
            
            #line 99 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.IncidencePer100k.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 99 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(county));
            
            #line default
            #line hidden
            this.Write("Rate>\r\n");
            
            #line 100 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"

        }
        foreach(var cca in allCcaNames) {
            var inc = current?.CCARates?.FirstOrDefault(pX=>pX.Name==cca);

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 105 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cca));
            
            #line default
            #line hidden
            this.Write("Abs>");
            
            #line 105 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.ConfirmedCases.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 105 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cca));
            
            #line default
            #line hidden
            this.Write("Abs>\r\n        <");
            
            #line 106 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cca));
            
            #line default
            #line hidden
            this.Write("Rate>");
            
            #line 106 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.IncidencePer100k.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 106 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cca));
            
            #line default
            #line hidden
            this.Write("Rate>\r\n");
            
            #line 107 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"

        }
        foreach(var hospital in allHospitalisedNames) {
            var inc = current?.Hospitalised?.FirstOrDefault(pX=>pX.Name==hospital);

            
            #line default
            #line hidden
            this.Write("        <Cases");
            
            #line 112 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 112 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.NumberOfCases.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</Cases");
            
            #line 112 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">\r\n        <CasesHospitalised");
            
            #line 113 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 113 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.CasesHospitalised.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</CasesHospitalised");
            
            #line 113 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">\r\n        <CasesHospitalisedPcnt");
            
            #line 114 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 114 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.CasesHospitalisedPercent.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</CasesHospitalisedPcnt");
            
            #line 114 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">\r\n        <CasesAdmittedToIcu");
            
            #line 115 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 115 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((inc!=null ? inc.CasesAdmittedToIcu.ToString() : "")));
            
            #line default
            #line hidden
            this.Write("</CasesAdmittedToIcu");
            
            #line 115 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hospital));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 116 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"

        }

            
            #line default
            #line hidden
            this.Write("    </Day>\r\n");
            
            #line 120 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"
    }
            
            #line default
            #line hidden
            this.Write("</Days>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\personal\CovidStats\CovidStats\DailyEpidemiologyXml.tt"

private global::System.Collections.Generic.List<CovidStats.DailyEpidemiology.HspcDailyEpidemiology> _DaysField;

/// <summary>
/// Access the Days parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<CovidStats.DailyEpidemiology.HspcDailyEpidemiology> Days
{
    get
    {
        return this._DaysField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool DaysValueAcquired = false;
if (this.Session.ContainsKey("Days"))
{
    this._DaysField = ((global::System.Collections.Generic.List<CovidStats.DailyEpidemiology.HspcDailyEpidemiology>)(this.Session["Days"]));
    DaysValueAcquired = true;
}
if ((DaysValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Days");
    if ((data != null))
    {
        this._DaysField = ((global::System.Collections.Generic.List<CovidStats.DailyEpidemiology.HspcDailyEpidemiology>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DailyEpidemiologyXmlBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
