// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CovidStats
{
    using System.Linq;
    using System.Collections.Generic;
    using CovidStats.SchoolsSummary;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SchoolWeeksXml : SchoolWeeksXmlBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<Weeks>\r\n");
            
            #line 8 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
    
 var allValueNames= Weeks.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.Values!=null)
                        pList.AddRange(pItem.Values.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allValueNames.Sort();

    var allFacilityResultSummary= Weeks.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.Values!=null)
                        pList.AddRange(pItem.AllFacilityTypesResultsSummary.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allFacilityResultSummary.Sort();

    var allSchoolsTesting= Weeks.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.Values!=null)
                        pList.AddRange(pItem.Schools.Testing.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allSchoolsTesting.Sort();

    var allSchoolsMassTesting= Weeks.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.Values!=null)
                        pList.AddRange(pItem.Schools.MassTesting.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allSchoolsMassTesting.Sort();



   var allChildcareTesting= Weeks.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.Values!=null)
                        pList.AddRange(pItem.Childcare.Testing.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allChildcareTesting.Sort();

    var allChildcareMassTesting= Weeks.Aggregate(new List<string>(),
                (pList, pItem) =>
                {
                    if(pItem.Values!=null)
                        pList.AddRange(pItem.Childcare.MassTesting.Select(pX => pX.Name));
                    return pList;
                }).Distinct().ToList();
    allChildcareMassTesting.Sort();
for(var i = 0;  i < Weeks.Count; i++) { 

            
            #line default
            #line hidden
            this.Write("    <Week>\r\n        <Number>");
            
            #line 67 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Weeks[i].Week));
            
            #line default
            #line hidden
            this.Write("</Number>\r\n        <SourceFileName>");
            
            #line 68 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Weeks[i].SourceFileName));
            
            #line default
            #line hidden
            this.Write("</SourceFileName>\r\n");
            
            #line 69 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"

        foreach(var item in allValueNames ) {
            var val= Weeks[i].Values.FirstOrDefault(pX=>pX.Name==item);
            var elementName = "Overall"+val.Name.Replace(" ", "").Replace("%", "").Replace("+", "");

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 74 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"Week"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 74 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.WeekValue));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 74 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"Week"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 75 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"Cumulative"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 75 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.CumulativeToDate));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 75 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"Cumulative"));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 76 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
      } 
        foreach(var item in allFacilityResultSummary) {
            var val= Weeks[i].AllFacilityTypesResultsSummary.FirstOrDefault(pX=>pX.Name==item);
            var elementName = "Overall"+val.Name.Replace(" ", "").Replace("%", "").Replace("+", "").Replace("*", "");

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 81 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 81 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoFacilities));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 81 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 82 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 82 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoTested));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 82 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 83 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 83 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 83 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 84 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 84 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoNotDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 84 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 85 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 85 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.DetectedPercent));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 85 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 86 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
      } 
        foreach(var item in allSchoolsTesting) {
            var val= Weeks[i].Schools.Testing.FirstOrDefault(pX=>pX.Name==item);
            var elementName = "SchoolsTesting"+val.Name.Replace(" ", "").Replace("%", "").Replace("+", "").Replace("*", "");

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 91 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 91 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoFacilities));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 91 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 92 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 92 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoTested));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 92 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 93 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 93 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 93 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 94 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 94 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoNotDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 94 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 95 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 95 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.DetectedPercent));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 95 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 96 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
      } 
        foreach(var item in allSchoolsMassTesting) {
            var val= Weeks[i].Schools.MassTesting.FirstOrDefault(pX=>pX.Name==item);
            var elementName = "SchoolsMassTesting"+val.Name.Replace(" ", "").Replace("%", "").Replace("+", "").Replace("*", "");

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 101 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 101 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoFacilities));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 101 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 102 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 102 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoTested));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 102 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 103 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 103 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 103 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 104 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 104 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoNotDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 104 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 105 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 105 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.DetectedPercent));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 105 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 106 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
      } 
        foreach(var item in allChildcareTesting) {
            var val= Weeks[i].Childcare.Testing.FirstOrDefault(pX=>pX.Name==item);
            var elementName = "ChildcareTesting"+val.Name.Replace(" ", "").Replace("%", "").Replace("+", "").Replace("*", "");

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 111 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 111 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoFacilities));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 111 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 112 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 112 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoTested));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 112 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 113 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 113 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 113 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 114 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 114 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoNotDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 114 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 115 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 115 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.DetectedPercent));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 115 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 116 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
      } 
      foreach(var item in allChildcareMassTesting) {
            var val= Weeks[i].Childcare.MassTesting.FirstOrDefault(pX=>pX.Name==item);
            var elementName = "ChildcareMassTesting"+val.Name.Replace(" ", "").Replace("%", "").Replace("+", "").Replace("*", "");

            
            #line default
            #line hidden
            this.Write("        <");
            
            #line 121 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 121 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoFacilities));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 121 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoFacilities"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 122 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 122 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoTested));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 122 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoTested"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 123 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 123 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 123 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 124 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 124 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.NoNotDetected));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 124 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"NoNotDetected"));
            
            #line default
            #line hidden
            this.Write(">\r\n        <");
            
            #line 125 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 125 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val.DetectedPercent));
            
            #line default
            #line hidden
            this.Write("</");
            
            #line 125 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(elementName+"DetectedPercent"));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 126 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
      } 
            
            #line default
            #line hidden
            this.Write("    </Week>\r\n");
            
            #line 128 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"
    }
            
            #line default
            #line hidden
            this.Write("</Weeks>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\personal\CovidStats\CovidStats\SchoolWeeksXml.tt"

private global::System.Collections.Generic.List<CovidStats.SchoolsSummary.HseSchoolsSummary> _WeeksField;

/// <summary>
/// Access the Weeks parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<CovidStats.SchoolsSummary.HseSchoolsSummary> Weeks
{
    get
    {
        return this._WeeksField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool WeeksValueAcquired = false;
if (this.Session.ContainsKey("Weeks"))
{
    this._WeeksField = ((global::System.Collections.Generic.List<CovidStats.SchoolsSummary.HseSchoolsSummary>)(this.Session["Weeks"]));
    WeeksValueAcquired = true;
}
if ((WeeksValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Weeks");
    if ((data != null))
    {
        this._WeeksField = ((global::System.Collections.Generic.List<CovidStats.SchoolsSummary.HseSchoolsSummary>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class SchoolWeeksXmlBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
